---
ID: "e9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b"
Parent: "d2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a"
Template: "e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"
Path: "/sitecore/templates/Branches/Project/click-click-launch/SYNC/Add AI Config/AI Config/FAQ/Product Categories"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Fields:
  - ID: "a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d"
    Hint: question
    Value: What product categories does SYNC sell?
  - ID: "b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e"
    Hint: answer
    Value: SYNC sells speakers (home, portable, professional), headphones (in-ear, over-ear, wireless), and amps (tube, solid state, digital, hybrid). We also offer accessories, SYNC for Business solutions, and Artist Services. Shop by category or use filters like Bluetooth and Smart speaker to find the right gear.
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260216T100000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3c"
